language: node_js
node_js:
  - "8"
after_success: yarn run coverage
deploy:
  provider: npm
  email: natalie@cuthbert.co.za
  api_key:
    secure: rzRCccJfVLDspjZwwyzzLZ0qNyU+qhwqGy+7cOF4dL8EBfPweiYFJCCcjYFw59VTFwcz8xE4rIecQP8aOE3aE8vY7H/Xhf3AJhrsHMKUT+yWxUHFlfp6DJOCFmDOkEY5gvL7U2cEzAaKGNz6hbH5MnHTH1n+uNS/RAgqYyXj2sbbXqoWUYReEIPEEUlT2HkWT4lv6MPN2GibuitZSHIGUynjj+NY1XKDlSZZB2CNCH/fwLSacgHIAmZfqAKNadwz2OFrRJsBNHsCslGgpZO9WeGDyEsrDkgMGrs/obXmFO52Ld0v2xXCb5UbP15PiQZYPCxOVkaLRLq2XWHXC36RGH0S8R9hM2E9698sitcQ37CvatTmbJjHTUPUsrQusZL45gAPnzmaO7nZ/1OGWHN1oztTjkniwNtNtOQmOOKe0T6vYqFGHHwmU0PNVB8psh4PmrR1YPtMTkZCiS8A16V3ISYghSjg9eIfRSPuhDFgAuCrKV1DMwxpX1PROd6J6NWd6EwtJ2jCS9kPb5zOufEBE71K3SK+OsOrn310gYjvSWziq/dTM6bdo4b+DyLUc9g34w90R47mwewa4Fz+VwVQWmehHE4xbg2YThSMk8hb0+cKogEFfOJ4NhisAW0Kgq/u3g9MvajPPooiqggGPSSRXJJVhjJuGijRQfXx9s//6gg=
  on:
    tags: true
    repo: ncthbrt/nact
    branch: master
notifications:
  slack:
    secure: uLOgivlomUhPxRBNEdqnLcFNCag+4xY1ibliDUvH3/h2+MEg2G+sd6FMd1QEpEIUEdzMV+Yhqoxrf9Goeq2hjKi5UbEB3ky9n8Yql6kRTmPeXfvVAMSU1UsQhGDX6IUyENpsywkm0A2QuMP/+3Z7EIXd9cQ4G6iLd3CT+aIXMCz7LY11WaLiwy1zYDoXDA0d6uYgUrUQB3k0TdUQlCC5DqoWJxCAYOawzrKZnrlfrX5VF2P4asLBAWWfEhuawhFVdRoWbE7T58Uw4YB51kG9p6ngtxMM5vLqqoOT+ARQIH/10+Tb/X7D596AuXZt6bBM4LSqaPTXMMlQk7AUTws3dg25wiJbfdPniMzJ8do+6xjf9vz2IE+PYLRU8xraOh5ZG8V2dK4QULpwww2Dbq7DE99kRrAqSMzrkZaklfILRvGSOsAgVrJsYdzuU5DGXGK28QpfGS/8ibcIuo253z+08GEmpgFFaHCH2eG7UiyOkdxjoGPDlkq7fjodhCx0TyS3VnWMrEJNw6+LU47LyFNuQZO9ra7rZdquISJHEnoR092zdS7M/niKvkxCLa22Lrbu4x5vRXW/WV8v28xnqNeFP4Bul6cyo0CefGYpy3LabvHJsJ6Ku6om0skDF7bOGptFvtEH3lWn4A06vqkE5n6UEQ51mHb5ms7ijwUpjd29bc0=
    on_success: change
    on_failure: always
